{{- if .Values.externalSecret.enabled }}
{{- $fullname := include "genesis.fullname" . -}}
{{- $store := .Values.externalSecret.store -}}
{{- $storeKind := .Values.externalSecret.storeKind -}}
{{- $refreshInterval := .Values.externalSecret.refreshInterval -}}
{{- if .Values.database.dsn.externalSecret.remoteKey }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $fullname }}-db
  labels:
    {{- include "genesis.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ $refreshInterval }}
  secretStoreRef:
    name: {{ $store }}
    kind: {{ $storeKind }}
  target:
    name: {{ default (printf "%s-db" $fullname) .Values.database.dsn.existingSecret }}
  data:
    - secretKey: {{ .Values.database.dsn.secretKey }}
      remoteRef:
        key: {{ .Values.database.dsn.externalSecret.remoteKey }}
        property: {{ default .Values.database.dsn.secretKey .Values.database.dsn.externalSecret.remoteProperty }}
{{- end }}
{{- if .Values.tls.externalSecret.remoteKey }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $fullname }}-tls
  labels:
    {{- include "genesis.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ $refreshInterval }}
  secretStoreRef:
    name: {{ $store }}
    kind: {{ $storeKind }}
  target:
    name: {{ default (printf "%s-tls" $fullname) .Values.tls.existingSecret }}
  data:
    - secretKey: {{ .Values.tls.secretKey }}
      remoteRef:
        key: {{ .Values.tls.externalSecret.remoteKey }}
        property: {{ default .Values.tls.secretKey .Values.tls.externalSecret.remoteProperty }}
{{- end }}
{{- if .Values.vault.externalSecret.remoteKey }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $fullname }}-vault
  labels:
    {{- include "genesis.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ $refreshInterval }}
  secretStoreRef:
    name: {{ $store }}
    kind: {{ $storeKind }}
  target:
    name: {{ default (printf "%s-vault" $fullname) .Values.vault.roleId.existingSecret }}
  data:
    - secretKey: {{ .Values.vault.roleId.secretKey }}
      remoteRef:
        key: {{ .Values.vault.externalSecret.remoteKey }}
        property: {{ default .Values.vault.roleId.secretKey .Values.vault.externalSecret.roleIdProperty }}
    - secretKey: {{ .Values.vault.secretId.secretKey }}
      remoteRef:
        key: {{ .Values.vault.externalSecret.remoteKey }}
        property: {{ default .Values.vault.secretId.secretKey .Values.vault.externalSecret.secretIdProperty }}
{{- end }}
{{- end }}
